ip: 127.0.0.1
port: 25565
name: null
sens: 0.003
qe_sens: 3.0
sound: false
keybindings:
  StrafeLeft:
  - KeyA
  Fire1:
  - KeyF
  MoveForward:
  - KeyW
  RotateRight:
  - KeyE
  ChangeCamera:
  - KeyC
  MoveBackward:
  - KeyS
  UnlockCursor:
  - KeyX
  Use:
  - KeyE
  StrafeRight:
  - KeyD
  RotateLeft:
  - KeyQ
  Fire2:
  - KeyQ
  Chat:
  - Enter
  Jump:
  - Space
  Mod1:
  - ShiftLeft
